server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

spring:
  cloud:
    gateway:
      routes:
        - id: user-service-users
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
        - id: user-service-auth
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: user-service-oauth2
          uri: http://localhost:8081
          predicates:
            - Path=/api/oauth2/**,/api/login/oauth2/**
          filters:
            - StripPrefix=1


